[package]
description = "to come"
edition = "2021"
license = "MIT"
name = "glabel"
repository = "https://github.com/chevdor/glabel"
version = "0.0.1"

[dependencies]
assert_cmd = "2.0"
clap = "=3.0.0-beta.4"
clap_derive = "=3.0.0-beta.4"
env_logger = "0.9"
futures = "0.3.18"
glabellib = {path = "../lib"}
hubcaps = "0.6.2"
log = "0.4"
tokio = {version = "0.2", features = ["full"]}
serde = "1.0"
serde_yaml = {version = "0.8", optional = false}

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
